### ISSUE TITLE
Nimble package?

### ISSUE THREAD

**Issue by 0atman** [juancarlospaco/nim-html-dsl#1]
How can I install this with nimble? Thanks!

**Comment by 0atman** [comment]
|`nimble install html-dsl` | :x: |
| ------------- |:-------------:|
|`nimble install nim-html-dsl` | :x: |

:confused:

**Comment by 0atman** [comment]
Hey @juancarlospaco, I see you never added this to Nimble - is that an oversight? https://github.com/nim-lang/packages/pulls?q=is%3Apr+author%3Ajuancarlospaco

**Comment by juancarlospaco** [comment]
Stuff not in Nimble is not finished.

**Comment by 0atman** [comment]
Oh, my apologies!

**Comment by 0atman** [comment]
I saw a confusing reference to `html_dsl` here https://framework.embarklabs.io/news/2019/11/18/nim-vs-crystal-part-1-performance-interoperability/ and thought it looked like a very :ok_hand: way of expressing html in nim.

I'll grab the code and try it out myself - thank you!

**Comment by juancarlospaco** [comment]
Nice I didnt know of the blog post. 
I think it starts failing when used nested elements, I dont remember exactly, but I am all the time doing things so...
