### ISSUE TITLE
Duplicated children

### ISSUE THREAD

**Issue by mantielero** [juancarlospaco/nim-html-dsl#3]
> Disclaimer ;oP: I am starting to use Nim with web technologies (I am new to both). 

When using `divs`, what it is underneath appears twice. As shown in the README:
```nim
    divs:
      p "Example"
```
produces:
```html
<div >
  <p > Example</p>
  <p > Example</p>
</div>
```

**Comment by juancarlospaco** [comment]
I recommend you to use https://github.com/karaxnim/karax
